name: CI
on: [push,pull_request]
jobs:
  CI_HEALTH_CHECK: 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dinka
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/dinka"
      NEXTAUTH_SECRET: dummy
      NEXTAUTH_URL: "http://localhost:3000"
      
      # Cloudinary (for image uploads)
      CLOUDINARY_CLOUD_NAME: dummy
      CLOUDINARY_API_KEY: dummy
      CLOUDINARY_API_SECRET: dummy
      
      # Email (for OTP verification)
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: 587
      EMAIL_USER: dummy
      EMAIL_PASS: dummy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm' 
      - name: Install Dependencies
        run: npm install
      - name: Database migrations
        run: |
          # Generate Prisma client
          npx prisma generate
          
          # Run database migrations
          npx prisma migrate deploy
          
          # (Optional) View your data
          # npx prisma studio
      - name: Build
        run: npm run build
          
        
